call DelFiles %0 :end_files
goto :end_files

\Windows\System32\adtschema.dll
\Windows\System32\advapi32res.dll
\Windows\System32\AggregatorHost.exe
\Windows\System32\AppXApplicabilityBlob.dll
\Windows\System32\AppXDeploymentClient.dll
\Windows\System32\AppXDeploymentServer.dll
\Windows\System32\AppxPackaging.dll
\Windows\System32\Apx01000.dll
\Windows\System32\ARP.EXE
\Windows\System32\AtBroker.exe
\Windows\System32\audioresourceregistrar.dll
\Windows\System32\autochk.exe
\Windows\System32\autofstx.exe
\Windows\System32\bcdprov.dll
\Windows\System32\bcdsrv.dll
\Windows\System32\bderepair.dll
\Windows\System32\blb_ps.dll
\Windows\System32\blbres.dll
\Windows\System32\bmrui.exe
\Windows\System32\BootMenuUX.dll
\Windows\System32\BootRec.exe
\Windows\System32\bootstr.dll
\Windows\System32\bootsvc.dll
\Windows\System32\bootux.dll
\Windows\System32\browseui.dll
\Windows\System32\C_G18030.DLL
\Windows\System32\c_GSM7.DLL
\Windows\System32\C_ISCII.DLL
\Windows\System32\cabapi.dll
\Windows\System32\cfmifs.dll
\Windows\System32\cfmifsproxy.dll
\Windows\System32\chkntfs.exe
\Windows\System32\cimfs.dll
\Windows\System32\CloudRecApi.dll
\Windows\System32\CloudRecoveryDownloadTool.dll
\Windows\System32\CloudRecSvc.exe
\Windows\System32\clusapi.dll
\Windows\System32\cmifw.dll
\Windows\System32\comcat.dll
\Windows\System32\compact.exe
\Windows\System32\CompPkgSrv.exe
\Windows\System32\ConhostV1.dll
\Windows\System32\ConsoleLogon.dll
\Windows\System32\convertvhd.exe
\Windows\System32\CoreMas.dll
\Windows\System32\CredentialUIBroker.exe
\Windows\System32\cryptdlg.dll
\Windows\System32\cryptext.dll
\Windows\System32\cryptoss.dll
\Windows\System32\cryptxml.dll
\Windows\System32\CSystemEventsBrokerClient.dll
\Windows\System32\ctac.json
\Windows\System32\d3d8thk.dll
\Windows\System32\d3d10.dll
\Windows\System32\d3d10_1.dll
\Windows\System32\d3d10_1core.dll
\Windows\System32\d3d10core.dll
\Windows\System32\d3d10level9.dll
\Windows\System32\d3d11on12.dll
\Windows\System32\D3D12Core.dll
\Windows\System32\dafWCN.dll
\Windows\System32\dafWfdProvider.dll
\Windows\System32\dbgeng.dll
\Windows\System32\DbgModel.dll
\Windows\System32\DefaultQuestions.json
\Windows\System32\delegatorprovider.dll
\Windows\System32\DetailedReading-Default.xml
\Windows\System32\DeviceCensus.exe
\Windows\System32\devicengccredprov.dll
\Windows\System32\DeviceSoftwareInstallationClient.dll
\Windows\System32\DeviceUpdateAgent.dll
\Windows\System32\dhcpcmonitor.dll
\Windows\System32\diagnosticdataquery.dll
\Windows\System32\diskraid.exe
\Windows\System32\dllhst3g.exe
\Windows\System32\dnscacheugc.exe
\Windows\System32\doclient.dll
\Windows\System32\domgmt.dll
\Windows\System32\doskey.exe
\Windows\System32\dosvc.dll
\Windows\System32\dpapimig.exe
\Windows\System32\dpx.dll
\Windows\System32\driverquery.exe
\Windows\System32\dskquota.dll
\Windows\System32\dtdump.exe
\Windows\System32\dxgwdi.dll
\Windows\System32\Eap3Host.exe
\Windows\System32\eapp3hst.dll
\Windows\System32\eappcfg.dll
\Windows\System32\eappcfgui.dll
\Windows\System32\eappgnui.dll
\Windows\System32\eapphost.dll
\Windows\System32\eapprovp.dll
\Windows\System32\eapputil.dll
\Windows\System32\eapsvc.dll
\Windows\System32\EapTeapAuth.dll
\Windows\System32\EapTeapConfig.dll
\Windows\System32\edgeIso.dll
\Windows\System32\EdgeManager.dll
\Windows\System32\efscore.dll
\Windows\System32\efssvc.dll
\Windows\System32\esentutl.exe
\Windows\System32\esevss.dll
\Windows\System32\ETWESEProviderResources.dll
\Windows\System32\eventcls.dll
\Windows\System32\expand.exe
\Windows\System32\f3ahvoas.dll
\Windows\System32\Facilitator.dll
\Windows\System32\fcon.dll
\Windows\System32\fdWCN.dll
\Windows\System32\finger.exe
\Windows\System32\fixmapi.exe
\Windows\System32\FlightSettings.dll
\Windows\System32\fltMC.exe
\Windows\System32\fltmgrres.dll
\Windows\System32\fmapi.dll
\Windows\System32\framedyn.dll
\Windows\System32\fstx.dll
\Windows\System32\ftp.exe
\Windows\System32\fverecoverux.dll
\Windows\System32\GdiPlus.dll
\Windows\System32\HalExtIntcLpioDMA.dll
\Windows\System32\HalExtIntcPseDMA.dll
\Windows\System32\HalExtPL080.dll
\Windows\System32\hbaapi.dll
\Windows\System32\hidserv.dll
\Windows\System32\HOSTNAME.EXE
\Windows\System32\HvSocket.dll
\Windows\System32\icfupgd.dll
\Windows\System32\icu.dll
\Windows\System32\icuin.dll
\Windows\System32\icuuc.dll
\Windows\System32\iemigplugin.dll
\Windows\System32\IESettingSync.exe
\Windows\System32\ifmon.dll
\Windows\System32\ifsutilx.dll
\Windows\System32\imaadp32.acm
\Windows\System32\imagelib.dll
\Windows\System32\imagesp1.dll
\Windows\System32\imapi.dll
\Windows\System32\imapi2fs.dll
\Windows\System32\imgutil.dll
\Windows\System32\IndexedDbLegacy.dll
\Windows\System32\inetcomm.dll
\Windows\System32\INETRES.dll
\Windows\System32\IPSECSVC.DLL
\Windows\System32\joinproviderol.dll
\Windows\System32\jscript9Legacy.dll
\Windows\System32\jsproxy.dll
\Windows\System32\kd_0C_8086.dll
\Windows\System32\kd_02_1af4.dll
\Windows\System32\kd_02_10df.dll
\Windows\System32\kd_02_10ec.dll
\Windows\System32\kd_02_14e4.dll
\Windows\System32\kd_02_15ad.dll
\Windows\System32\kd_02_15b3.dll
\Windows\System32\kd_02_19a2.dll
\Windows\System32\kd_02_1137.dll
\Windows\System32\kd_02_1414.dll
\Windows\System32\kd_02_1969.dll
\Windows\System32\kd_02_8086.dll
\Windows\System32\kd_07_1415.dll
\Windows\System32\kdcom.dll
\Windows\System32\kdnet.dll
\Windows\System32\kdnet_uart16550.dll
\Windows\System32\KeyCredMgr.dll
\Windows\System32\kmddsp.tsp
\Windows\System32\l2nacp.dll
\Windows\System32\localkdcsvc.dll
\Windows\System32\lodctr.exe
\Windows\System32\lpk.dll
\Windows\System32\manage-bde.exe
\Windows\System32\mapi32.dll
\Windows\System32\mapistub.dll
\Windows\System32\MBR2GPT.EXE
\Windows\System32\mibincodec.dll
\Windows\System32\Microsoft.Windows.Storage.Core.dll
\Windows\System32\Microsoft.Windows.Storage.StorageBusCache.dll
\Windows\System32\microsoft-windows-battery-events.dll
\Windows\System32\microsoft-windows-hal-events.dll
\Windows\System32\microsoft-windows-kernel-pnp-events.dll
\Windows\System32\microsoft-windows-kernel-power-events.dll
\Windows\System32\microsoft-windows-kernel-processor-power-events.dll
\Windows\System32\microsoft-windows-pdc.dll
\Windows\System32\microsoft-windows-sac-events.dll
\Windows\System32\microsoft-windows-sleepstudy-events.dll
\Windows\System32\microsoft-windows-storage-tiering-events.dll
\Windows\System32\microsoft-windows-system-events.dll
\Windows\System32\mimofcodec.dll
\Windows\System32\mispace.dll
\Windows\System32\mlang.dat
\Windows\System32\mprmsg.dll
\Windows\System32\MRINFO.EXE
\Windows\System32\msadp32.acm
\Windows\System32\msafd.dll
\Windows\System32\msaudite.dll
\Windows\System32\mscat32.dll
\Windows\System32\msg711.acm
\Windows\System32\msgsm32.acm
\Windows\System32\mshtml.dll
\Windows\System32\msimtf.dll
\Windows\System32\msobjs.dll
\Windows\System32\msoert2.dll
\Windows\System32\mspatcha.dll
\Windows\System32\mspatchc.dll
\Windows\System32\msrating.dll
\Windows\System32\mssign32.dll
\Windows\System32\mssip32.dll
\Windows\System32\msvcirt.dll
\Windows\System32\mtxdm.dll
\Windows\System32\muifontsetup.dll
\Windows\System32\MuiUnattend.exe
\Windows\System32\nbtstat.exe
\Windows\System32\nci.dll
\Windows\System32\netiohlp.dll
\Windows\System32\netlogon.dll
\Windows\System32\ngclocal.dll
\Windows\System32\NL7Lexicons0804.dll
\Windows\System32\NL7Models0804.dll
\Windows\System32\normnfc.nls
\Windows\System32\normnfd.nls
\Windows\System32\normnfkc.nls
\Windows\System32\normnfkd.nls
\Windows\System32\nrtapi.dll
\Windows\System32\nshdnsclient.dll
\Windows\System32\nshwfp.dll
\Windows\System32\ntfsres.dll
\Windows\System32\ntkrla57.exe
\Windows\System32\ntprint.dll
\Windows\System32\ntprint.exe
\Windows\System32\odbccp32.dll
\Windows\System32\odbcint.dll
\Windows\System32\odbctrac.dll
\Windows\System32\offlinelsa.dll
\Windows\System32\offlinesam.dll
\Windows\System32\OLD9AD4.tmp
\Windows\System32\OLD9AF4.tmp
\Windows\System32\OLD9B05.tmp
\Windows\System32\oleacchooks.dll
\Windows\System32\OneSettingsClient.dll
\Windows\System32\OpcServices.dll
\Windows\System32\pacjsworker.exe
\Windows\System32\perfc009.dat
\Windows\System32\perfd009.dat
\Windows\System32\perfdisk.dll
\Windows\System32\perfh009.dat
\Windows\System32\perfi009.dat
\Windows\System32\perfnet.dll
\Windows\System32\perfos.dll
\Windows\System32\perfproc.dll
\Windows\System32\PkgMgr.exe
\Windows\System32\plutonfw_AuthenticAMD.dll
\Windows\System32\pngfilt.dll
\Windows\System32\pnpdiag.dll
\Windows\System32\pnppolicy.dll
\Windows\System32\pnpui.dll
\Windows\System32\PnPUnattend.exe
\Windows\System32\polstore.dll
\Windows\System32\poqexec.exe
\Windows\System32\prfc0804.dat
\Windows\System32\prfd0804.dat
\Windows\System32\prfh0804.dat
\Windows\System32\prfi0804.dat
\Windows\System32\prflbmsg.dll
\Windows\System32\print.exe
\Windows\System32\printui.dll
\Windows\System32\ProductEnumerator.dll
\Windows\System32\profext.dll
\Windows\System32\provthrd.dll
\Windows\System32\prvdmofcomp.dll
\Windows\System32\PSModuleDiscoveryProvider.dll
\Windows\System32\psmodulediscoveryprovider.mof

;PPPOE
;\Windows\System32\rasauto.dll
;\Windows\System32\rasautou.exe
;\Windows\System32\raschap.dll
;\Windows\System32\raschapext.dll
;\Windows\System32\rasctrs.dll
;\Windows\System32\rasdiag.dll
;\Windows\System32\rasdlg.dll
;\Windows\System32\rasmans.dll
;\Windows\System32\rasmbmgr.dll
;\Windows\System32\rasmontr.dll
;\Windows\System32\rasppp.dll
;\Windows\System32\rastapi.dll
;\Windows\System32\rastls.dll
;\Windows\System32\rastlsext.dll
;\Windows\System32\sstpsvc.dll
;\Windows\System32\prxyqry.dll

\Windows\System32\rasctrnm.h
\Windows\System32\rdrleakdiag.exe
\Windows\System32\recdisc.exe
\Windows\System32\recover.exe
\Windows\System32\ReFsDedupSvc.exe
\Windows\System32\RefsDedupSvc.Proxy.dll
\Windows\System32\refsutil.exe
\Windows\System32\Register-CimProvider.exe
\Windows\System32\ReInfo.dll
\Windows\System32\remoteaudioendpoint.dll
\Windows\System32\repair-bde.exe
\Windows\System32\ResetEngine.dll
\Windows\System32\ResetEngine.exe
\Windows\System32\ResetPluginHost.exe
\Windows\System32\ResetTelemetry.dll
\Windows\System32\resutils.dll
\Windows\System32\ROUTE.EXE
\Windows\System32\rstrui.exe
\Windows\System32\runexehelper.exe
\Windows\System32\sacsess.exe
\Windows\System32\sacsvr.dll
\Windows\System32\schedcli.dll
\Windows\System32\scrobj.dll
\Windows\System32\sdhcinst.dll
\Windows\System32\setbcdlocale.dll
\Windows\System32\setup.bmp
\Windows\System32\setupetw.dll
\Windows\System32\sfc.exe
\Windows\System32\smbwmiv2.dll
\Windows\System32\smphost.dll
\Windows\System32\softpub.dll
\Windows\System32\spaceutil.exe
\Windows\System32\SpatialAudioLicenseSrv.exe
\Windows\System32\spp.dll
\Windows\System32\sppnp.dll
\Windows\System32\sprefs.dll
\Windows\System32\srclient.dll
\Windows\System32\srcore.dll
\Windows\System32\storagewmi.dll
\Windows\System32\storagewmi_passthru.dll
\Windows\System32\streamci.dll
\Windows\System32\subst.exe
\Windows\System32\svsvc.dll
\Windows\System32\sxstrace.exe
\Windows\System32\sysreset.exe
\Windows\System32\tapi32.dll
\Windows\System32\tbs.dll
\Windows\System32\tcpmib.dll
\Windows\System32\TCPSVCS.EXE
\Windows\System32\tdhres.dll
\Windows\System32\tier2punctuations.dll
\Windows\System32\TimeBrokerClient.dll
\Windows\System32\TimeBrokerServer.dll
\Windows\System32\tokenbinding.dll
\Windows\System32\TpmCertResources.dll
\Windows\System32\TpmCoreProvisioning.dll
\Windows\System32\TRACERT.EXE
\Windows\System32\TrustedSignalCredProv.dll
\Windows\System32\TSSessionUX.dll
\Windows\System32\ttlsauth.dll
\Windows\System32\ttlscfg.dll
\Windows\System32\tzres.dll
\Windows\System32\ucsvc.exe
\Windows\System32\uiomapapi.dll
\Windows\System32\UnionFSApi.dll
\Windows\System32\unlodctr.exe
\Windows\System32\UpdateAgent.dll
\Windows\System32\UpdateCompression.dll
\Windows\System32\updatepolicy.dll
\Windows\System32\utcutil.dll
\Windows\System32\uudf.dll
\Windows\System32\verifier.dll
\Windows\System32\verifier.exe
\Windows\System32\verifiergui.exe
\Windows\System32\VhfUm.dll
\Windows\System32\vmbuspipe.dll
\Windows\System32\vpnike.dll
\Windows\System32\vpnikeapi.dll
\Windows\System32\vss_ps.dll
\Windows\System32\VSSVC.exe
\Windows\System32\w32topl.dll
\Windows\System32\wbadmin.exe
\Windows\System32\wbengine.exe
\Windows\System32\WcnApi.dll
\Windows\System32\wcncsvc.dll
\Windows\System32\WcnEapPeerProxy.dll
\Windows\System32\WcnNetsh.dll
\Windows\System32\wcnwiz.dll
\Windows\System32\wdigest.dll
\Windows\System32\wdscapture.exe
\Windows\System32\wdscapture.inf
\Windows\System32\wdsclient.exe
\Windows\System32\WdsCommonLib.dll
\Windows\System32\wdscsl.dll
\Windows\System32\WdsDiag.dll
\Windows\System32\WdsImage.dll
\Windows\System32\wdsmcast.exe
\Windows\System32\WdsServerCommonLib.dll
\Windows\System32\wdstptc.dll
\Windows\System32\webplatstorageserver.dll
\Windows\System32\webservices.dll
\Windows\System32\WEBSOCKET.DLL
\Windows\System32\werdiagcontroller.dll
\Windows\System32\WerEnc.dll
\Windows\System32\WerFault.exe
\Windows\System32\WerFaultSecure.exe
\Windows\System32\wermgr.exe
\Windows\System32\werui.dll
\Windows\System32\Windows.Devices.HumanInterfaceDevice.dll
\Windows\System32\Windows.Devices.Midi.dll
\Windows\System32\Windows.Internal.UI.Logon.ProxyStub.dll
\Windows\System32\Windows.Storage.OneCore.dll
\Windows\System32\Windows.System.RemoteDesktop.dll
\Windows\System32\winipsec.dll
\Windows\System32\winload.efi
\Windows\System32\winload.exe
\Windows\System32\winlogonext.dll
\Windows\System32\winsku.dll
\Windows\System32\wlancfg.dll
\Windows\System32\wlandlg.dll
\Windows\System32\wlanext.exe
\Windows\System32\wlanpref.dll
\Windows\System32\wmiprop.dll
\Windows\System32\wmitomi.dll
\Windows\System32\wosc.dll
\Windows\System32\wpr.config.xml
\Windows\System32\wpr.exe
\Windows\System32\wpx.dll
\Windows\System32\ws2help.dll
\Windows\System32\wship6.dll
\Windows\System32\WSHTCPIP.DLL
\Windows\System32\wuapi.dll
\Windows\System32\wuauclt.exe
\Windows\System32\wuaueng.dll
\Windows\System32\wups.dll
\Windows\System32\wups2.dll
\Windows\System32\wusys.dll
\Windows\System32\XAudio2_8.dll
\Windows\System32\XAudio2_9.dll

:end_files
